### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by mgmalana** [tryolabs/norfair#104]
I'm using Norfair and another library. However, I'm getting a version conflict for rich. 

Is it possible to change the dependency of norfair to be able to use higher version of rich? I'm using poetry to install norfair and I'm getting a `"SolveProblemError Because norfair (0.4.0) depends on rich (>=9.10.0,<10.0.0)"`. I need to use at least version 11.2.0. 

I can force install higher version of rich using pip but I think it would be cleaner if the dependencies are clear. Norfair seems to work fine even with higher version of rich.,

**Comment by joaqo** [comment]
Hi, thanks for the feedback! We're experiencing [some issues](https://github.com/tryolabs/norfair/projects/1#card-80389759) with our installation flow in general, so this feedback is really useful for us to consider this case in our fixes. Would you mind sharing which other dependency is having issues with rich so we can test our fixes?

**Comment by mgmalana** [comment]
@joaqo  thank you for your reply! I'm trying to use [BentoML ](https://github.com/bentoml/BentoML) library. It needs >=11.2.0 or else the library will raise an error as described here [issue](https://github.com/bentoml/BentoML/issues/2377). Thank you very much for your work in norfair!

**Comment by joaqo** [comment]
Awesome, thanks, we'll look into it!

**Comment by sebastian-correa** [comment]
We're experiencing a similar issue when trying to use `norfair` coupled with `lightning`. While `norfair` implicitly depends on `typing-extensions(>-3.7.4,<4.0.0)` due to a direct dependency on `rich(>=9.10.0, <10.0.0)`, `lightning` has a direct dependency on `typing-extensions(>=4.0.0, <4.3.1)` [[reference](https://github.com/Lightning-AI/lightning/blob/58014846ee0fb54b92e4bfb4c0965b72bc0a9641/requirements/pytorch/base.txt#L13)]. Note that `lightning` also places a direct constraint on `rich` [[reference](https://github.com/Lightning-AI/lightning/blob/58014846ee0fb54b92e4bfb4c0965b72bc0a9641/requirements/pytorch/extra.txt#L11)].

For the time being, we have resorted to using an older version of `pip` with the `--no-deps` flag to force the installation of the seemingly incompatible packages.

It would be very useful if you bumped`norfair`'s `rich` version.

**Comment by nmichlo** [comment]
Please may this be prioritized. This is a major block for use with other projects.

**Comment by javiber** [comment]
Hey @nmichlo We are working on this at the moment.
I will make a PR as soon as poetry finishes locking the dependencies... that might take a while

**Comment by dekked** [comment]
#160 is merged, so this issue is finally solved!

For now and before we do the next release on PyPI, please install Norfair from GitHub `master` branch.
