### ISSUE TITLE
Bad results on the detectron2 example

### ISSUE THREAD

**Issue by sadimoodi** [tryolabs/norfair#129]
Hello,
I have tired your detectron2 example on my video and i got very bad results, tracking is lost when even a minor occlusion happens, tried different detectron2 models but the results were consistently bad.
any parameters to optimize?

**Comment by aguscas** [comment]
Hello sadimoodi! I don't know what may be causing your specific problem, but take into account that the distance function used in the detectron2 demo doesn't take into account the size of the objects or the resolution of your video, since it is just the unscaled distance between the centers. If your video has really high resolution, then the distance between objects can be large even for objects that appear to be close in the video. You can try re scaling the `distance_function` to take into account you video resolution and change the `distance_threshold` accordingly, or using a completely different `distance_function`. 

If you think that your objects are getting deleted too fast, you can increase the `hit_counter_max` parameter so that the objects live longer without detections. 

On another note, I do not know the quality of your detections. In case you do not have consistent detections (for example, if you are missing detections during really minor occlusions), try lowering the detection threshold of your detector and try lowering the `detection_threshold` argument you are currently using in the tracker (if you are using any non `None` value).

If you want to share your video with us so we can see it, it might be helpful in order to give you better advices.

**Comment by nikky4D** [comment]
@aguscas  How do you take into account the size of the objects or the resolution of the video in the distance function? is it just dividing the norm by the video resolution?  What would be the best strategy to incorporate this into the distance function and tracker?
> account the size of the objects or the resolution of your video, since it is just the unscaled distance between the centers. If your video has really high resolution, then the distance between objects can be large even for objects that appear to be close in the video. You can try re scaling the distance_function to take into account you video resolution and change the distance_threshold accordingly
