### ISSUE TITLE
bounding box from tracked object

### ISSUE THREAD

**Issue by nikky4D** [tryolabs/norfair#131]
I have detections that have returned bounding boxes. I can run the tracker with centroids. However, I would need to still get out the new locations of the tracked bounding boxes. 

I find that using bounding boxes performs worse than using centroids on my dataset. So is there a way I can update the bounding boxes using the tracking information? Concretely, can I pass in the box centroids (which does better than extrema points) as input to the tracker, while adding in bounding boxes as `Data` parameter for `Detection` object and , then update the `Data` parameter with tracker location?  How would I pull out the vector that updates the location and apply that to the data parameters?

**Comment by facundo-lezama** [comment]
Hi @nikky4D! 

I didn't completely get the information you'd want to update in the `Data` parameter. If you are tracking centroids, what should the bounding box's dimensions be after an update? Should it remain the same as the original? Because in my experience, bounding boxes change their shape over time, which is also tracked when updating the `Tracker` object.
