### ISSUE TITLE
Tracking a self defined bounding box

### ISSUE THREAD

**Issue by DemonIncarnate** [tryolabs/norfair#143]
Hi, I am trying to run a tracker on a self defined bounding box . I am basically defining a bbox around an object by creating a norfair Detection object giving manual xywh coordinates and defining a score . 
But when i run tracker.update() on these detection objects to return a tracked_objects an empty list.

**Comment by aguscas** [comment]
Hello @DemonIncarnate , there might be many reasons why the update method is returning an empty list:

- The tracker will start returning a `TrackedObject` once its `hit_counter` is greater than the `initialization_delay` you are using in your `tracker` instance. Therefore, if you called the `tracker.update()` method passing your detection objects only once, your `tracker.update` method will return an empty list if your initialization delay is greater than 0. However, you can check if the tracked object has indeed been created checking the `tracker.tracked_objects` list. This is done this way so that the tracker needs to accumulate evidence from several frames to conclude that your detections were not just false positives from your detector. 
- If the scores you are using in your detections is less than the `detection_threshold` of the tracker.
- If the `distance_threshold` is too small for the specific `distance_function` you are using (for example, if your distance functions is 1/IoU, then the distance between a `TrackedObject` and a `Detection` instance will always be greater or equal to 1, so you should use a distance_threshold greater than 1, otherwise tracked_objects and detections would never match).

**Comment by DemonIncarnate** [comment]
Hello @aguscas  , thanks for the insight , changing the max_hit_counter seem to work.
Closing the issue. Thanks a lot for quick response.

**Comment by devAmoghS** [comment]
@DemonIncarnate Can you please share your snippet here explaining how did you integrate the manual bbox with Tracker from Norfair.

I am working on a similar problem where I intend to pass bbox generated by the SelectROI from OpenCV to the Tracker function but I think it needs the Detection() instead. Is it feasible to convert the OpenCV detection to a format accepted by Norfair ?

**Comment by facundo-lezama** [comment]
Hi @devAmoghS! 

To transform the bounding box generated by `SelectROI` from `OpenCV` you can use something like this:

```python
bbox_xywh = cv2.selectROI("Select object", frame)
bbox_xyxy = np.array(
    [
        [bbox_xywh[0], bbox_xywh[1]],
        [bbox_xywh[0] + bbox_xywh[2], bbox_xywh[1] + bbox_xywh[3]],
    ]
)
norfair_detection = Detection(points=bbox_xyxy)
```

But please consider what we discussed in https://github.com/tryolabs/norfair/issues/240: Norfair is designed to be fed with detections (you can skip some frames if you need) and not to track an object in a video from a single initial detection.
