### ISSUE TITLE
visualising bboxes/masks

### ISSUE THREAD

**Issue by SharifElfouly** [tryolabs/norfair#23]
Hey, how about an extension for the `Detection` class and `drawing.py` to add bboxes and masks to directly visualize them?

Do you think this would fit norfair?

**Comment by joaqo** [comment]
Hey, thanks for the proposal! We are currently in the process of merging support for MOT metrics into the library, which includes a bbox drawing function, so that capability will soon be added. Regarding segmentation, I don't think it currently fits into Norfair's use cases, though I may be wrong.

I think for the time being these capabilities won't be needed, but I really appreciate the ideas. Any other ideas you have are most definitely welcome. Thanks!

**Comment by nachonacho2** [comment]
Hi, I just wanted to add a note of support for the proposed functionality of drawing masks. I think it would be really helpful to be able to visualise the predicted segmentation in addition to the centroid spot. This will help to verify the quality of the detections.
Thanks!

**Comment by joaqo** [comment]
Hey @nachonacho2 thanks for the feedback. I think we'll add mask drawing through https://github.com/tryolabs/norfair/pull/24/files as it seems to be something people need, doesn't really expand norfair's surface area too much, and is easy to implement. So stand by for it!
