### ISSUE TITLE
How to remove a tracked object

### ISSUE THREAD

**Issue by blakeblackshear** [tryolabs/norfair#266]
**Describe the situation you are working on**
In my implementation, I want to stop tracking an object sometimes even when it is still visible.

**Describe what is it that you need help with**
I want to delete a tracked object from the tracker by the track id.

**Comment by facundo-lezama** [comment]
Hi @blakeblackshear! 

You can always access the complete list of tracked objects on `tracker.tracked_objects` and modify it as you need. That's not a common thing to do with Norfair, but you can do it.

To better understand your situation, what do you expect to happen after you remove the track from the tracked objects? Because you're saying that the object will still be visible, so I understand that you will be having future detections of that same object, right?

**Comment by blakeblackshear** [comment]
We have a setting to disable tracking on an object after a certain number of frames where the object has been stationary. Think of a parked car. Some would rather have the same car as separate tracked objects for the time that it entered the driveway and parked from the time where it left hours later.

And yes, the parked car can and does sometimes get picked up again.

This also helps in situations where a car is driving by and something in the background gets detected as a false positive and the tracker keeps tracking the false positive indefinitely. If you never expect objects to be stationary beyond a threshold, you can end the track by assuming it's a false positive.
