### ISSUE TITLE
IOU distance threshold

### ISSUE THREAD

**Issue by mesllo-bc** [tryolabs/norfair#268]
I'm implementing the `yolov5` demo example on the `norfair` repo using the `iou` as the distance function.  

I noticed that for the `Tracker` class there's the `distance_threshold` parameter defined as below

```
distance_threshold : float
        Defines what is the maximum distance that can constitute a match.
        Detections and tracked objects whose distances are above this threshold won't be matched by the tracker.
```
I can understand that when using Euclidean distance this threshold definition makes sense. Distances higher than the threshold between detections and tracked objects are deemed as too far away. However, when using the `iou` as the metric, wouldn't it make sense if distances **below** a certain `iou` value are deemed as too far away?

For instance, if we set `0.7` as the distance threshold for `iou`, the definition of this threshold dictates that an `iou` of higher than `0.7` is too far away, when the idea of an `iou` is that the higher it is, the stronger the match right? Am I missing something here? I couldn't find where this threshold is defined specifically for the `iou` so I decided to ask here! Thanks :)

**Comment by facundo-lezama** [comment]
Hi @mesllo-bc, I'm glad you are trying to use Norfair!

You are correct in that the definition becomes tricky when it comes to IoU. Our implementation of `iou` actually considers that, and we use `1 - iou` as the result of the distance function. You can see this here: https://github.com/tryolabs/norfair/blob/9b315b4cfa5f9cf145f068a21a2b7673703ac9e3/norfair/distances.py#L379

So if you want to consider only those IoU values that fall above 0.7, you should use `distance_threshold = 0.3`.

We do this to be consistent in the definition of the `distance_threshold` so that as the threshold gets lower, you are becoming more restrictive in your matches.

**Comment by mesllo-bc** [comment]
Yes this clarification is great! Makes more sense now, thanks! :)
