### ISSUE TITLE
getting error while building docker image

### ISSUE THREAD

**Issue by sanskarupjao** [tryolabs/norfair#275]
When i'm trying to run run_gpu.sh it's giving me this error, "ERROR: failed to solve: process "/bin/sh -c cmake     -D BUILD_PYTHON=ON     -D BUILD_CAFFE=ON     -D BUILD_EXAMPLES=ON     -D GPU_MODE=CUDA     -D USE_CUDNN=OFF     -D CMAKE_BUILD_TYPE=Release     -D DOWNLOAD_BODY_COCO_MODEL=ON     -D DOWNLOAD_BODY_MPI_MODEL=ON     -D DOWNLOAD_HAND_MODEL=OFF     -D DOWNLOAD_FACE_MODEL=OFF     .." did not complete successfully: exit code: 1". please check and help me out

**Comment by aguscas** [comment]
Hello! Sorry for the late response. The issue you are experiencing seems to be more related to Openpose rather than Norfair, more in particular when downloading the models. You might find this [link](https://cmu-perceptual-computing-lab.github.io/openpose/web/html/doc/md_doc_05_faq.html#download-server-down) useful, especially the _Download Server Down_ error in the FAQs. I will have to look deeper into it. If you have already managed to fix it, please let us know so we can update the dockers.
