### ISSUE TITLE
Embeddings in TrackedObject

### ISSUE THREAD

**Issue by LorBordin** [tryolabs/norfair#36]
Hi, 

I'm trying to implement a tracker which uses embedding.
I'm storing each embedding in the detection.data, however I also need a place where to store the TrackedObject embedding, in order to compute a suitable  distance.
Is there something similar to  detection.data for TrackedObject?

**Comment by joaqo** [comment]
Hi, @LorBordin! Thanks for trying Norfair. I am currently working in this exact use case. Which is resulting in changes to Norfair's API to make it easier to use embeddings for tracking. These changes are still not pushed though, so for the time being you'll have to access `TrackedObject.last_detection.data` to access the embedding of last detection associated with a tracked object. This is not ideal of course.

The design I am working on now saves the X amount of last detections of each tracked object, which are distributed homogeneously across the lifetime of each tracked object, so they are representative of how the tracked object looked through its life. This is perfect for my use case, but now that I have you here, I'd like to ask you if this would work for you? Or would you prefer a different design?

**Comment by LorBordin** [comment]
Hi @joaqo! Thanks for reaching me.
yours is a very good idea, I think it could work well if the object undergoes a long phase of occlusion, in this case it could increase the robustness of the tracker. I'm very curious to try it!
Just to be sure I've correctly understood: do you randomly sample across the lifetime of each tracked object and then you compute one distance for each of the samples?

My idea, instead, was save for each TrackedObject an embedding which is the averaging of the last X detections. 
I've already implemented this its works good but I'd like see a comparison with your idea.

**Comment by joaqo** [comment]
My idea was for each TrackedObject to keep X (which the user can chose) amount of detections through its life. These detections will have to be continuously resampled to span the changing life of the object, I have a cool little algorithm for this. Then the user can do whatever they like with these detections, compare them all to the new incoming detections to see if they match, take their average and then compare, whatever.

Your idea sounds interesting, you would need for me to save the last X detections of each tracked object for it to work right? Or how are you managing to do it now?

**Comment by LorBordin** [comment]
I've already done it thanks. I've added a method to the TrackedObject class that stores and updates an embedding.

**Comment by joaqo** [comment]
Thats great! So you store an update the embedding by doing something like a rolling average on it I assume? How is it working?

**Comment by LorBordin** [comment]
Yes, exactly. 
It stores the last X embeddings of the trackedObject and computes the average vector, which will be used to calculate the distance with the new detections.

**Comment by joaqo** [comment]
Gotcha, thanks!

**Comment by codethief** [comment]
Hi there! I'd also be very much interested in equipping my TrackedObjects with data. It's pretty much the one feature that's keeping me from trying out Norfair in my project. In my case, I'm detecting and tracking hands and, on top of that, I'm also running a classifier that tells me what gesture the hand is currently showing. In my own naive tracker implementation (I only came across Norfair a few days ago), I use the gesture class for the distance function (a gesture cannot change arbitrarily fast) but I also compute a rolling average of the gesture scores of the last X hand detections belonging to a tracked hand. That way, gesture classification ends up being more stable across time and random misclassifications cannot cause havoc further down the pipeline.

Unfortunately, my own tracker is rather slow (again it's a rather naive implementation), so Norfair looks really cool and I'd be really interested in hearing how far along that new code of yours is @joaqo! :)

> The design I am working on now saves the X amount of last detections of each tracked object, which are distributed homogeneously across the lifetime of each tracked object, so they are representative of how the tracked object looked through its life.

Just to reiterate, in my case I'd be interested in the last X detections (as opposed to X detections across the the object's entire lifetime) since a hand's gesture might change over time.

**Comment by joaqo** [comment]
Gotcha, thanks for the feedback @codethief ! I am currently trying our version of Nofair + embeddings and its working really well. We still have to create a good demo and update the documentation before we publish it. It will support X past detections. Stay tuned!

**Comment by codethief** [comment]
@joaqo Sweet! Looking forward to it!

**Comment by Surya059** [comment]
Hi @joaqo. Do you have any timeline in mind for the release of version with embeddings feature?

**Comment by joaqo** [comment]
Hi, I think it should be in the next month or so!

**Comment by TWilliamson95** [comment]
> Hi, I think it should be in the next month or so!

Hi, any news on this? I'd love to use Norfair in my university MSc project

**Comment by joaqo** [comment]
Hi @TWilliamson95, we have been very busy with other commitments and therefore Norfair development did not advance at the pace we would like, but starting August we already have budgeted time specifically for Norfair dev. I'll be personally in charge of adding support for embeddings (its already half built), so I would expect it for September.

Apologies for the delay, hope it's not too late for using it in your project.

**Comment by fcakyon** [comment]
@joaqo is there any updates on this as of 20th september?

**Comment by joaqo** [comment]
Hey @fcakyon, we had some unexpected things come up which delayed our progress by some weeks, we are working on this though! Expect it in a few weeks.

**Comment by joaqo** [comment]
It took longer than expected but https://github.com/tryolabs/norfair/pull/74 implements this feature, you can try it locally or wait for our next release which will happen soon.

**Comment by terechko** [comment]
Hi @joaqo, thanks a lot for the excellent tracker!

Following up on the comment from @codethief I was wondering if there is a possibility to store N last _consecutive_ detections? If I understand the code well, the `conditionally_add_to_past_detections()` enforces omissions of detections in the `past_detections` list to keep the uniform distribution since the birth of the object tracking.

Thanks in advance!

**Comment by javiber** [comment]
Hi @terechko, Glad you find Norfair useful!

You understood correctly the code, indeed we are enforcing one way of sampling `past_detections`.

We have planned a review of embeddings and re-id in this quarter, as part of it, one of the things we will likely tackle is this limitation. We need to give users the flexibility to select other strategies for sampling, specially last-N detections which seems like a common one.

In the meantime, the best I can offer is to monkey-patch the function:

``` python
from norfair.tracker import TrackedObject

def last_n(self, detection):
    if self.past_detections_length == 0:
        return
    self.past_detections.append(detection)
    self.past_detections = self.past_detections[-self.past_detections_length :]

TrackedObject._conditionally_add_to_past_detections = last_n
```

It's not pretty but it should work
