### ISSUE TITLE
Max inertia

### ISSUE THREAD

**Issue by ddd-20** [tryolabs/norfair#44]
What happens when the hit inertia counter hits `hit_inertia_max`? 
As per docs, `hit_inertia_max` defines how large inertia can grow, and therefore defines how long an object can live without getting matched to any detections. But does `hit_inertia_min` dictate how long an object lives before being destroyed for not getting matched?

**Comment by joaqo** [comment]
Hi, thanks for the question! You got it exactly right. If the inertia counter gets below `hit_inertia_min` the object gets destroyed.

**Comment by dtoopran** [comment]
Then what is `hit_inertia_max` for?

**Comment by ddd-20** [comment]
Then what is `hit_inertia_max` for? What happens when hit inertia counter reaches this value?

**Comment by joaqo** [comment]
Hit inertia max is so that we don't continue adding inertia ad infinitum to each object.

Lets say I have an object that has been getting tracked for 10 minutes, if I didn't set a cap to the maximum inertia it could accumulate during its lifetime, it would take 10 more minutes of no detections for the object to disappear, which is not what we want. We want the time it takes for an object to get 'untracked' to have certain independence on how much time it has lived.
