### ISSUE TITLE
tracker with detected people body with haarcascade

### ISSUE THREAD

**Issue by Hilal-Urun** [tryolabs/norfair#67]
Hi, thanks for your explanations first :) I want to ask instead of using yolo, I want to use opencv haarcascade for real time body detection, Could you guide me for this purpose?

**Comment by haviduck** [comment]
this tracker is meant to be easily added to any tracker, and they supply some examples but that question is better asked over at opencv. however a quick search got me this:
https://github.com/imhighoncoffee/body-detection-haar

so if you alteir their detect.py to read frames from video instead of an image thats a good start. then aggregate a detection list in the format they require and pass it to tracker.

**Comment by Hilal-Urun** [comment]
thank you so much !! @haviduck

**Comment by dekked** [comment]
@Hilal-Urun Norfair is agnostic to the detector you are using.

Therefore, you should make sure your detector is running, and then the integration should be fairly trivial. Please check the provided examples.

I am closing this issue for the moment.
